### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by w1770946466** [577fkj/mimotion#13]
Run pip install --upgrade pip
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages (22.0.2)
Collecting pip
  Downloading pip-22.0.3-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 41.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2
Successfully installed pip-22.0.3
Collecting requests
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 8.4 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 11.7 MB/s eta 0:00:00
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.11-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 KB 24.2 MB/s eta 0:00:00
Collecting certifi>=20[17](https://github.com/w1770946466/mimotion/runs/5091581699?check_suite_focus=true#step:4:17).4.17
  Downloading certifi-[20](https://github.com/w1770946466/mimotion/runs/5091581699?check_suite_focus=true#step:4:20)[21](https://github.com/w1770946466/mimotion/runs/5091581699?check_suite_focus=true#step:4:21).10.8-py2.py3-none-any.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 KB [25](https://github.com/w1770946466/mimotion/runs/5091581699?check_suite_focus=true#step:4:25).5 MB/s eta 0:00:00
Installing collected packages: certifi, urllib3, idna, charset-normalizer, requests
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.11 idna-3.3 requests-2.27.1 urllib3-1.[26](https://github.com/w1770946466/mimotion/runs/5091581699?check_suite_focus=true#step:4:26).8
参数有误: list index out of range
Error: Process completed with exit code 1.

**Comment by 577fkj** [comment]
请认真核对参数 如果不使用推送也请输入off

**Comment by w1770946466** [comment]
![image](https://user-images.githubusercontent.com/63459931/152773077-95e14342-437b-417d-b0cb-71ce614fa098.png)

**Comment by 577fkj** [comment]
参数中不能有空格之类的 也不能为空 你重填一次参数试试

**Comment by w1770946466** [comment]
重填之后还是这样
![image](https://user-images.githubusercontent.com/63459931/152774654-d21e7745-e07c-4eb7-921a-5b29c3f6baf0.png)

**Comment by w1770946466** [comment]
step里填的0
pkey里填的1914492138:AAENFE40dRpcq5tGtNOOdB1vyURoohxxxxxx@1116181xxx
pwd里填的小米帐号密码
user里填的手机号
pmode里填的tg

**Comment by 577fkj** [comment]
目前我也不清楚是什么原因 我有时间重写一下配置部分 目前是没办法了

**Comment by w1770946466** [comment]
~~发现了原来是我填错位置了~~

**Comment by honghongtu** [comment]
> ![image](https://user-images.githubusercontent.com/63459931/152773077-95e14342-437b-417d-b0cb-71ce614fa098.png)

参数是填在action secrets
