### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhouyong9898** [577fkj/mimotion#14]
大佬，最近action运行报错，麻烦看看是什么原因呢：
Traceback (most recent call last):
  File "main.py", line 314, in <module>
    push += main(user_list[line], passwd_list[line], step) + '\n'
  File "main.py", line 73, in main
    login_token,userid = login(user,password)
  File "main.py", line 51, in login
    login_token = r2["token_info"]["login_token"]
KeyError: 'token_info'
Error: Process completed with exit code 1.

**Comment by 577fkj** [comment]
登录失败 你自行检查一下

**Comment by zhouyong9898** [comment]
感谢大佬，估计是网络原因，我重新运行了一下可以了
