### ISSUE TITLE
请问怎么在腾讯云函数运行啊？

### ISSUE THREAD

**Issue by Liujishou** [577fkj/mimotion#5]
请问怎么在腾讯云函数运行啊？

**Comment by 577fkj** [comment]
pip install requests
python3 main.py pmode pkey user Pwd step

**Comment by Liujishou** [comment]
> pip install requests
> python3 main.py pmode pkey user Pwd step

我将main.py 里的代码复制过去 在设置变量里添加了pmode pkey user Pwd step 运行后没成功

**Comment by 577fkj** [comment]
把 pmode pkey user Pwd step 替换成环境变量名字

**Comment by Liujishou** [comment]
> 把 pmode pkey user Pwd step 替换成环境变量名字

![截屏2021-08-09 下午9 08 07](https://user-images.githubusercontent.com/79367462/128712254-1e00df34-6793-4b72-87f0-e47e829bdcf3.png)

**Comment by Liujishou** [comment]
> 把 pmode pkey user Pwd step 替换成环境变量名字
tx是py3.6的。 你代码3.8的 是不是这个问题？

**Comment by 577fkj** [comment]
pip install requests
python3 main.py $pmode $pkey $user $Pwd $step
