### ISSUE TITLE
运行 出错，大佬看下

### ISSUE THREAD

**Issue by Egnus-s** [577fkj/mimotion#6]
Error: Process completed with exit code 1.

**Comment by 577fkj** [comment]
请附上完整日志

**Comment by Egnus-s** [comment]
Run pip install requests
Collecting requests
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2021.5.30 charset-normalizer-2.0.4 idna-3.2 requests-2.26.0 urllib3-1.26.6
WARNING: You are using pip version 21.2.2; however, version 21.2.3 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.7.11/x64/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "main.py", line 380, in <module>
    passwd = sys.argv[4]
IndexError: list index out of range
Error: Process completed with exit code 1.

**Comment by 577fkj** [comment]
请确定参数是否正确
