### ISSUE TITLE
步数不能刷了，希望能更新

### ISSUE THREAD

**Issue by leejanevan** [577fkj/mimotion#8]

**Comment by 577fkj** [comment]
请附上完整日志

**Comment by leejanevan** [comment]
![image](https://user-images.githubusercontent.com/46781192/129676647-d7589710-385b-4d1e-90b3-d340cd2d0969.png)显示成功，实际步数没有刷成功，账号已注销重新注册过了

**Comment by XuthusWong** [comment]
遇到同样问题

**Comment by 577fkj** [comment]
进过测试确实已经失效，有时间我会修复

**Comment by leejanevan** [comment]
麻烦大佬了

**Comment by hzerebus** [comment]
我已经找到方法修复了。

**Comment by 577fkj** [comment]
已修复
