### ISSUE TITLE
请教一下直接执行main.py 推送报错.

### ISSUE THREAD

**Issue by likexi** [577fkj/mimotion#9]
我下载了main.py到debian服务器里面.     想让脚本服务器里面运行

我执行命令  python ./main.py wx SCT91805T1uCHkVqeYGTCSKf9Az5itojK 13243086333 zxcvbnm123 29033
报错:   1324****6333: [2021-11-05 08:44:03] 修改步数（29033）success
 Traceback (most recent call last):
  File "/a/main.py", line 596, in <module>
    push[Pm]()
  File "/a/main.py", line 504, in to_push_wx
    push_wx(self.pkey, self.push_msg)
AttributeError: 'ToPush' object has no attribute 'push_msg'

步数是修改成功了.  但是推送报错,   能否指点一下 需要修改哪里才能使用的.

**Comment by BlueHtml** [comment]
@likexi 已提[PR](https://github.com/577fkj/mimotion/pull/10)，也可以参考这个[修复后的仓库](https://github.com/BlueHtml/mimotion-1)

**Comment by 577fkj** [comment]
感谢帮忙修复
